### ISSUE TITLE
Fix shuffling bug

### ISSUE THREAD

**Issue by thiderman** [drunkenfall/drunkenfall#146]
As evidenced by the previous tournament, something can go wrong when we reshuffle the players.

My current (yet unverified) thought is that shuffling accidentally creates more matches than needed. This is probably an effect from when the matches were flattened (from having `playoffs`, `semis` and `final` as separate struct fields).

* [ ] Check if this is solved by simply removing all matches before shuffling
* [ ] Add unit tests that confirm

**Comment by yasakbulut** [comment]
I believe 5f40e8ed9d7bdb5352063e152d8b3ef9b5d715dc will solve this 🤞
