### ISSUE TITLE
Check semi logic for bugs

### ISSUE THREAD

**Issue by thiderman** [drunkenfall/drunkenfall#147]
The final bug that stopped the previous tournament was that the start button softlocked because the interface did not properly realize that the first semi could be started. IIRC this was because the tournament thought it had _3_ semis instead of two, which got it confused.

This needs verification and fixing if so. Most of the logic problem is probably in the frontend.
Relates to #146, or is at the very least caused by it.

It's possible that a workaround is to have a `FORCE START` button that lets the match start regardless of the semi state. Not great, but would have kept the last tournament running.

**Comment by yasakbulut** [comment]
So, starting a tournament fails the following `TestStartingGivesTheRightAmountOfPlayoffs` expectation: `15 player tournament had 11 matches, not 4`.

So I'm pretty sure that #146 is the root cause of this.
