### ISSUE TITLE
Remove initial API call from frontend

### ISSUE THREAD

**Issue by thiderman** [drunkenfall/drunkenfall#27]
Since we now always set up the websockets, the frontend will get the first state immediately and as such the original API call to get them is pointless unless the websockets fail.
- [ ] Make sure the backend websocket handler loads the initial state on boot
- [ ] Remove the API call from `TournamentList.vue`
- [ ] Make sure all pages load the initial data, regardless of URL

**Comment by frontierpsycho** [comment]
I began a little work on this, not sure if it's still needed (since everything seems to work with the API call for now).

Any more pressing things?

**Comment by thiderman** [comment]
Could you make a PR perhaps so I can take a look? :)

The most pressing thing right now is the color correction, and I am working on that right now. Other than that, any pick of the issues is a good go! Maybe check for the frontend label primarily?

**Comment by frontierpsycho** [comment]
https://github.com/thiderman/drunkenfall/pull/43
