### ISSUE TITLE
Implement the header to be a vue component

### ISSUE THREAD

**Issue by thiderman** [drunkenfall/drunkenfall#4]
- [ ] Build the breadcrumbs from a list of link objects (current implementation has no navigation back...)
- [ ] Same as above, but for the links
- [ ] Add `:not(first-child):before` CSS classes that add a stylized `/` between the items in the breadcrumbs
- [ ] Replace all current usages of the header with this new component

**Comment by frontierpsycho** [comment]
Btw, the vue router hijacks the browser's back button, so hitting back should actually work as you expect, ie, hitting back from the Join screen will correctly load the TournamentPreview and so on. So the breadcrumbs might be nice, but you can probably do without them.

**Comment by thiderman** [comment]
The header has been replaced by the sidebar, which is 100% a reusable compontent!
