### ISSUE TITLE
Add stage selection

### ISSUE THREAD

**Issue by thiderman** [drunkenfall/drunkenfall#41]
We want to be able to have defined stages per match. Probably randomized from a finite list, so that we don't repeat levels. Normal levels for tryouts, Dark World for Semis and Cataclysm for the final.
- [x] Set selections upon generating the tournament
- [ ] Display in frontend

**Comment by frontierpsycho** [comment]
Not sure if you know this, but:

> Note that stages can be eliminated from the random selection pool by pressing the Left Trigger button when highlighted. 

From [here](http://towerfall.wikidot.com/tournament-handbook). All around useful info.

**Comment by thiderman** [comment]
Fixed in recent commits.
