### ISSUE TITLE
There is an extreme lack of ASCII art in the source code

### ISSUE THREAD

**Issue by thiderman** [drunkenfall/drunkenfall#94]
```
________                      __                 ___________      .__  .__   
\______ \_______ __ __  ____ |  | __ ____   ____ \_   _____/____  |  | |  |  
 |    |  \_  __ \  |  \/    \|  |/ // __ \ /    \ |    __) \__  \ |  | |  |  
 |    `   \  | \/  |  /   |  \    <\  ___/|   |  \|     \   / __ \|  |_|  |__
/_______  /__|  |____/|___|  /__|_ \\___  >___|  /\___  /  (____  /____/____/
        \/                 \/     \/    \/     \/     \/        \/           
```

**Comment by kallekrantz** [comment]
```
 ____  __._______________  __.____  __.________    _______    _______  ___________ _______   
|    |/ _|\_   _____/    |/ _|    |/ _|\_____  \   \      \   \      \ \_   _____/ \      \  
|      <   |    __)_|      < |      <   /   |   \  /   |   \  /   |   \ |    __)_  /   |   \ 
|    |  \  |        \    |  \|    |  \ /    |    \/    |    \/    |    \|        \/    |    \
|____|__ \/_______  /____|__ \____|__ \\_______  /\____|__  /\____|__  /_______  /\____|__  /
        \/        \/        \/       \/        \/         \/         \/        \/         \/ 
```

**Comment by mgoeppner** [comment]
```                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                          
                                                                                                                   ``````````                                                                                                                             
                                                                                                       ````...----:-:::::::::/::::-.``                                                                                                                    
                                                                                                 ``..--::------------.--------::/+++++/::-.`                                                                                                              
                                                                                             `...-----.--...-..--------.-..--::::::://+++++++/:.`                                                                                                         
                                                                                         `.....---....`....-.....------------:::/://::///+++oooo+:-`                                                                                                      
                                                                                      `......................----...----------::/://////://+++oosoo+/.                                                                                                    
                                                                                   ``...-.....................----.----:----------:::///+/+///+++ooooo/.`                                                                                                 
                                                                                ``..-..............`.....````..............--.-------:::://///++++oooooo+/.`                                                                                              
                                                                             ``....-.........````..```..```````````.......---...---.--:::::///++++++ooooooo+/.                                                                                            
                                                                           `.............`````.``````````````````````.`..----:-----.---:-:::::/+/+ooosssooooss/.                                                                                          
                                                                          .......`....-.````````````````````````.`..``.......--.-----------:::///++ossssoooooooo/.                                                                                        
                                                                       ``.......`....-.````````.``````````````````...`.`.....--..::-:....---:::///+oooossosoooooo+:`                                                                                      
                                                                      .....``.....``.`.````````.`.```````````````````.`......--..------------:///+/o/++osossssooooo+.                                                                                     
                                                                    `.....`......``.```....``````````````````````````..``.....-.....---:------:/++/+/++ossssssssooooo-                                                                                    
                                                                   `......`..`...`..```.`.`````````````````````````.`..`.`.........-.--:-------:////+ooooosssssssossso:                                                                                   
                                                                  `.....```.```.`.```````````````````````````````````.``.`..............-------:://+/+oososssssssssssss:                                                                                  
                                                                  --..`.``````````````````````````````````````````.`...`.`.............------::::/:/+++oooosssssssssssss-                                                                                 
                                                                 .-...`.```.````.````````````````````````````````````..`...`............------:::://+/+osssssysssssssssss.                                                                                
                                                                `:.```.```.``````````````````````````````````````````.`....`.........``..--------:/://++sssssssssssssssss+                                                                                
                                                                .-.`.```.````.````````````````````````````````````````..``...``........-..-----:/::///++ossssosyssssssssss.                                                                               
                                                                :.``.``..````````````````````````````` ``````````````...```...`..`........-.--:-:/:///oossyssssyssysssssss+`                                                                              
                                                               `:.`.```.`````.````````````````` ``````````````````````..`........`......--...--.-:-/+oossyysssosyysssssssss:                                                                              
                                                               -:..``.```````.````.``````````````````````````````````.`.`..........--..-.-.----.--/+sosssyssssysysyyysssssyo.                                                                             
                                                               :-..`.`.```````````.-.````````````````````````````````..``..-.......-.----.---.-:-:yhssoossyysyyyyyyysssyyssy/                                                                             
                                                               :-.````....`.```.````````````````````````````````````..``..........-.-:--:--.---::/+osysossyyyyyyyyyyysyyyssss`                                                                            
                                                               --.`.```..```.````.`````````````````````````.``````.`.```..........-.---:-------::/+/+ossysssyssyyyyyyysyysyys.                                                                            
                                                              `:-..`..`.-..`...`.``.````````.`````.```````..`````.`..``........-....---:-------:://+oososssssyyyyyyyyyyyysyyy:                                                                            
                                                              .:-..`......``...`.```````````.`````...`.`.`.`````..`.`...-.-...........------.:::://syssooosssyyyhyyyyyyssysyy/                                                                            
                                                              -:.-.....-.`.``.`..``````````````````..`..`....`..............`.........----------:/++ooooo+osyyyyyyyyyyyyyysss/                                                                            
                                                              -:.-.`.....`````..`.````````````````````.........-..```.....``.........----------::/++oooo+ooosyyyhyyyyyyyyysss+                                                                            
                                                              ----.`.`.....``.`-`.`````````````````````........-``````.`..``...`.....---:-----:::/++ooo+++oooyhyyyyyyyyyyysyy+                                                                            
                                                              .....`...-..-..``````````````````````````.....-.....````.`..`.``.......--::-.-:::://///+///+oosyhyyyyyyyhhyyyyso                                                                            
                                                              `.`.-....-.....```````````````````````````.`...-..-.````.......`.`....-::/:--::-:::-::::::::+osyyyhyyyyyhhyyyyys`                                                                           
                                                              `-...-.`..-..``````````````````.``.```````.``.....-.`````.-.....`..-..:---....--....---:-:-:/osyyyyysyyyhhyyyyys`                                                                           
                                                              `....-..`....`````````````````````...`.```........--...-.--..`..``...........--:----::-----:/oyyhhyyyyyyyyyyhyyo                                                                            
                                                              `-...-.......``````````````````````......-...-..----.-.:---.````````.``...-::////::::-------:oyhhhhyyysyhhhhhhdy/` .//+/`                                                                   
                                                        `````  -.....-......`````````````````````````...``.....-:----:::..```.`...---:/+oossso+//::::///++oshddddhhhhhdddddmmmhoossoyyo`                                                                  
                                                      `..```..+d/.......--..`````````````.------...``````.``-...::.--:::.....-::://+oosyyyyhhhhyyyyyyyyhhddddddmmmmNmddmmmmmmdhhyyyhddd-                                                                  
                                                      .:+-```.dmd/-.-----:----.-------:://+ooooooo++////+/::--..::.--:/-...:/oyhhhhhhhhhhhyyssooooooo+ooyyyyyyyhdmmmmNmmmmmmdhddyhhddmd.                                                                  
                                                      .-+/-.`:mdmdyhhhhhysoo+//+++++oooooossyyhhhdddddmmmmmdyyo++/:-:://+ohdmmmmddhyysyhhhhhhhyyhhyhhyyhhddhhhhhyyymmNmdmmmddddddhhhddy`                                                                  
                                                      `.-:.-`/mdyhddhhhysooo++++/////++++++ooosssyyyyhddmmmmmmmmmdhhddmmNNmmmmmdddddhhdddhmmhmmdmmhhddhyhdddddhdmdysmmmmmmddddddhyyyhhs`                                                                  
                                                       .`--.`:ddyhddhhyso::::/+oosyhyysyyhhdmdmddmddddhhhhmmmdmmmmmmmmmmmmmmmdmmmddddddhs/ohdddhdhoosddysyyhdddddhysymmmdmddddhhhhhyyyo                                                                   
                                                       ``.:-`.yddmdddy/oh+::-/oshmmdys+shdhddddyyhdyyssy+oshmddmmmmmmmmmmmmmdmmmdddddhhs+/:+osso+//+syhhsooyhdddhyyy+dddhmdddhhhhhyyyy/                                                                   
                                                        ``-.``+dmdddyo./ddy+::oshyssso+//++ooo++osoyyysso+++dddmmmdmmmmmmNNmhmmddddhyssso+//:::::/+oosssssooyhddyyyyssmdmmdhhddyyyyyyy-                                                                   
                                                        ``..``/mmmddo:.:dddhyosss/+oo/:::..-:--:/+++oosoo++:oddmmddmmmmmmNNNyhhddddhyoo+/:::----///++++//+++oydhhyyyy+dmmmhyhmmddhyyys`                                                                   
                                                         `....:mmmmhy:..ohhddhhy+/+/::-----...---::://++/:--/dddmmmmmmmmmmNNyyhhhhhyso+:-----.--:::++/--://osshhyyyhy:dmmdhyyhmdddyyy+                                                                    
                                                         `.``.-mmmmho..:-+hdhhys+++/-....--..`.--::::--:----/mdmh+/:--/odmmmhyyyysssoo+/:::----::///:-:-:/+ossyyyyyyy-hmmhyhysymddhyy-                                                                    
                                                          .`.--smddho-.-:-:shhyo++/:-...------::-:---.--....+mmd/..``.-:smmNmsyyso+oo+/+//:-::---:/::--:://osyyyyyyso:mmmdyhyysdmdhyy-                                                                    
                                                          .``---hdhho/`.::--+so+//-.....--::/-.----...-...`.odm+.`````.:+ydmmhsys//++/////+/::://:::/:::/++oyhhyyyy++/Nmmhhhhyydmdhyy.                                                                    
                                                          ```.--+hhd+//.-::-:////:-..``..-....-.....-.-.`.-:ddo.`.```..-:+ydmmyhh+:////:::::::::::::::::/+osyhyyyy+++ymmmhhhhyhddysos`                                                                    
                                                          `.``.--hhho+//.::::+/+/:-...-..----............:+smy....````.-/+syhNNhhy+:-:/:::::/::::/:::://+osyhhhyyoo/+mmmdhhhyhhyysoso                                                                     
                                                           ``````sdhh+++:-:/:++++:-...::---.-......-....:oodd-.-..```..-/+syydmNhyso:-:::::--:/:://///++syyhdyyys+:ommmmhhhhhdysosyy-                                                                     
                                                            `.-``:dhdy+++-:-:/ooo+:--..-----........-.-/+sdm+--...```.../osyhdmNmmhyo/::-:---::::///+++osyyyo+//+ydmmmdhhhhhyssooyho                                                                      
                                                            `..```/dhdh+//:::-/+so/::-...-.-.......-:://ydh+:--...```..-/+syhdmmmmmmmdyso++/:::/:/://+///++oshhdddhhhhhhdhhhyssyyyy.                                                                      
                                                             .`````+syhhyo+/:-.-/sso/::---:-.---:/+++syhy/-.-.....````.-:+shdddysydmNmdddhhhhhhhyyyyyyyyhhddddhhhhhhdhhhhdhhhhhhyy/                                                                       
                                                              ...``:+://+syyyhysoo++//:::::/+++ossyhddd/-.........```...:/syhhhsooyhmmdhs++////+oosssyyyyhhhhhyhhhhhhhhhhdhhdhyhy/                                                                        
                                                              .....://:--::--:::/+ooooo+o++ooo+ooosyso/--.........`...--:+yhhyssssyhhddhyo+:-----://+osyhhyyssyyyhhhhhhhhhhhyhyy+                                                                         
                                                              `-...-://:-::--....--::::::-------:/++---::+os+----.----:/+yhdhhhdhhddddhyyo+/:-...::/+oyyhhyyssyyhhhhdhhhdhhhhhh+`                                                                         
                                                               `---.-/+:-:---.......----.....---://-..-:oyyo+/-::/+oossshdmmmmmmdddhyyysooo+/:----::+osyhhysssyyhhhhdhhddhddds:                                                                           
                                                                 .--:/+:-::--...-....-.-----..-://-.....-:/:-:.---:/oossyhdhhdhyyssssysoo++++/:---:/+osyhhysssyyhhhhhhhddh/+:`                                                                            
                                                                   `..-/:-::---.......-.--...--/::...........-..-...::-.-:/++++/++++oooooo++++/---:/++syhhysosyhhhhhhhhdd/                                                                                
                                                                      `/::::---....-.--.....-::+:......-....``````..-:-...-::://://:/++o+++/+os:---//+syhhssosyhhhhhhhddd-                                                                                
                                                                       .///::---....----...-:/+/-.........`.``````..-::...::::::-://:+/++////+os:--:/+syhhssssyhhhhdddddmd/`                                                                              
                                                                        -+++:---.....---.---:++-..........`.`.......-::.----::::-//////++/////oys:--:/osyhyssyyyyhhddhdmNNNh:`                                                                            
                                                                         -o+/::-...-..-----:/o:-.........``....-....----.---::::://:////+++++/+sh+---:+oyyyssyyhhhdddddmNNNNmy-                                                                           
                                                                          -+/::--.....---.-:/s-..-...........---------:----:////:///o++osos+++/shy-.-:/+yyyssyyhhhddmmNNNNNNNNms-`                                                                        
                                                                           -++:---.-.-..---:/o:..-------...-------:-:/:---:://+o+o+osssyyyso+++shs-..-/oyyhysyyhhddmmmNNNNNNNNNNms-`                                                                      
                                                                    ``.-:+shdy/-------...--::/:---::://:::::::::::://////+ssyyyyhhhhdddddhys++oyh+...-/osyhyyyyhhdmmdhNNNNNNNmNNNNms-                                                                     
                                                               `.:+shmNNNNNNNNh:::----.-------::///oossooooooosssssyysssydddhhyhhhhsyyyhhddhsosss-...-:oyhhyyyyhdmmdyoNNNNNNNNmmNNNNms-`                                                                  
                                                `````````..-:oydNNNNNNNNNNNNNNNy:----:----:-.---/osyyo/:::::::::::-----:::-:::-/://::/osyyyhy++//.`..-/oyhhyssyhdmdhooNNNNNNNNNNNNNNNNmy-`                                                                
                                       ``.-:/osyyhhhhdddmNNNNNNNNMNNNNNNNNNNNNNNo::-::-----..--::++/---...-...````````-`...-.-.-:/+:+ooooossy+/::..`.-/oyyyssyhdmdhy/sNNNNNNNNNmNNNNNNNNNy:`                                                              
                           ``.-:://+osyhdmNNNNNNNNNNNNNNNNNMNNNNMNNNNNNNNNNNNNNNm+:--::----..-://:.-.--............--:-.-:-::-::/oo+/o+/+++oo+::-....-/syyysyhdmdhh+:sNNNNNNNNNNNNNNNNNNNNNms:`                                                           
                   `.-:/oshdmmmmNmmmNNNNNNNNNNNNNNNNNNNMNNNNMNNNNNMMNNNNNNNNNNNNNd/---:--...--://................--:::--:////://++//////+++//+:::-...-+syyyshdddhhs::hNNNNNNNNNNNNNNNNNNNNNNNNds:`                                                        
              .-+sydmmNNNNNmNNmmmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNh/---------:::-.`.............--------:::::::///:-::+////://:::/:.-:+yhhyhddmdhh::/mNNNNNNmNNNNNNmNNNNNNNNNNmmNdo-                                                      
         `.:ohmmmNmNNNNNNNNNmNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNh:-.------::-..``.`......`..---------::-:--///:--::/:://:/+:/:++///shddhddmddh+-:yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNdo:`                                                  
    .:+shmmNNmNmNNNNNNNmNNNmNNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh:-------:--...```....`.`...-`..```......-.::---.-:-//:::::+ooooosyhdhhdmddh+-:/mNNNNNNNNNNmNNNmNNNNNNNNNNNNNNNNNNNmy+-`                                              
-+sdmmmmmNNmNmNmNNNNmmmmmNNmmNmNNNNNmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNh/::-------...````````````````.........----:--..---::::://+ssyyyyhdddddmmd+-::dNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNds/`                                           
mmmmNNmNNNmmmNNNNNNNNNmmmNNNNNNNNNNNNmmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNy://::---.--..``````````````````......--..:---.---:::://+shhhhdddddmmmdh/-::yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmy/.                                        
mmmmNNNNNmmmmmmNNNmmNNNmNmNNNNNNNNNNNNNNmNmNNNNNNNNNNNNNMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNs`.:+oo+/:::-..`````````````.```....`...--:------::////oohmmmmmmmmmmmdy:-:-yNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmh+.                                     
mmmmmmNmNmmmmmmmmmmmmmmNNmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNs`````.-/+o/:-.``..`````````...`.....-.--::-----::/+/++shdmmmmmmmmmmho--:-sNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmdy+.                                  
mmmmmmmmmmmmNmmmmmmmmmmmmmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNy``     `.:///-.`.```````.`......-.-.-:/:/-/----://++oshmmmmmmmmmmdy/--:-sNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmNNmmNNNNmmmh+-`                              
mmmmmmmmmmmmNNmmmmmmmmNmmmmNNmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNy``  `    ..-:/-........`.-..-:---::-::/:/::-:://+oooydmmmmmmmmdddo:-:::yNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNmNNNNNNNNNNNNNmNmNNNNNNNmNmNmmhs/.                           
mmmmmmmmmmmmmmmmmmmmmmmmNmNNNmNmmmmNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNmmNNNh````` `  ``.--::--..----.--::--:/+/:://++/:://+ossydmmmmmmmdmmds/-::-:hNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNmmmdho:.                       
mmdmmmmmmmmmNmNmNmmmmmmNNNNNNmNNmmNmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmmNmmmNmNd.`   `  ` ``...--:::::-::://:://+oo+o+/o++o+osyhddmmmmdmmmmdds/--:--/dNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNmmmNmmdho:.                   
mmmmmmmmmmmmNNNNNNmmmmmNNNNNNmmNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmNNNNmm-`  `  ``  ``...-.-/ooooossyyyyyyhysssyyhhhhhddddddmmmddmdds/:-----omNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNmNNNNNNNNNNNmmmNNNNNmdy+-`               
mmmmmmmmmmmmmNNNNmNmmmmmNNNNNmNNmNNmmmNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNmmmmNmNmm-`  `  ` `````..-..:shhyso+oydddhhhhhhhdddddhhddmdmdddmdho:-------sNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmNmmNNNmNmmmmmmmNmNNNmmmmmhs/.`           
mmmmmmmmmmmmmmNmNNNNNNNNNNmNNNNNmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNm:` ` ` `   `````.../ss+:---/sys++++sso+ossydddddhhhhhhs/-.......-yNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmmmmmmmmmmmNNNNNmmmmmmmmmmmmmmmmmNNmdyo-`        
mmmmmmmmmmmmmNNNNNNNmmmmmNmNNNNNmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmm:```````   ``  ``..:/:-....:/:::::/os+-:/sdddhysssso/-`````````:dNNNNNNNNNNNNNNNNNNNNNNmNNNNmNNmmNNNNNNNNNNNNNNmNmmmmmmNNmmmmNNNNNNNmmmmmmmmmmNNNNmmNmmmmmhs+:.    
mmmmmmmmmNmmNNNNNmNNmmNmmmmNNNNNNNNmmmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmd-``` ` ``       `...-.....-------:/os+.-/sddysoo+:-``````````.+dNNNNNNNNNNNmNmmNNmNNNNNmNNNmNNNNNNNmNNNNNNNNNNNmNmNmmNNmmNmmmNNNmmNmmNmNmmmmmmmmNNmmmNmmmmmmmmdy+-`
mmmmmmmmmmmmNNNNNmmmmmNNNNmNNNNNmNmmNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNmNNmmmd-`````  ``    ` ```.......-----:::+oyo--+syso+:.````````````-yNNNNNNNNNNNNNmNmNNNNNmNNNNNNNmNmNNNNNmNNNNNNNNmNNNNmmNNNNNNNmNmNNmmmmNNNmNmmmmmmmmmNmmmmmmmmmmmmmmmdh
mmmmmmmmmmmmNNNmmmmmmmmNmmNNNNNNNmmNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNmmmNmmmd-` `   `     ```````..`..-:::--:/+ooso::+ss+-``````````````/dNNNNNNNNNNNNNNmmNNmNmmmNNmNmNNNmmNNNNNNNNNNNNNNNNNNNNNNNNmmNmmmmNNNmmmNmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmNNNmmmmmmmmmNmNNNNNNmNmNNNmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmNNNNmmNNNmmdh.    `       `````  ``..-:////++oo+++o//o/.``````````````.smNNNNNNNNNNNNNNNNNNNmmNmmNNNNNNNNNNmNmNNNNNNNNNNNNNNmNNNNmNNmNmmmmmmmNmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmNmmmmmmmmNNNNNNNNNNNNNNmmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmdds` ` `` `` `````````````-.-/+osssoo+++:-.````````````````-hNNNNNNNNNNNNNNNNNmmNmmmNmmNNNNNNNNNNmmmNmNNNNNNNNNNNNNmmmNmNmmNNmmmmNmmNmmNmmmNNmmmmNmmmmmmmmmmmmmmmmmmmm
mmmmmmmmNmmmmmmmmmmmmmmmNNNNNNNNNNNmNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNmdho``   ``` ``` ````````::````.-::::/+:.``````````````````-dNNmNNNNNNNNNNNNmNNNmmNmmmmNNNNNNmNNNNNmmNmNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmNmmmmmNNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNmdh+`` ``   ```  ` ````.......:osso+:-````````````````````/dNNNNNNmNNNNNNNNmNNNNNNmNmmmmNmNNNNmNNNNNNNNmNNNNmNNmmNNNNmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNmmmNNmNNNNNNmdy: ```````  ``` ````....-/sdNmNmNNmmy.`````````````````ommmNNNNNNNNNNNNNNNNNmNmmNmmmmmNNmmNNmNNmmmmmNmNNNmmNNmNNmNNmNmNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdm
mmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmNmNNNNmhy.` `````  ` `` ```..:shmNNNNmmNmNmmNd-``````````````.yNmNNNmmNNNNNNNNNNmmNNmmmmmmmmNmmmmmNNNNmNmmNNNNNNNNNNNNNNNmmmmNmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
mmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNmNNNNmNmhs``  ` ``    ```..-sdNNNNNNNmNNNNmdhssy:````````````-hNNNNNNNNmNmNNNNNmNmmmNNmmmmNmmNmmmmNmmNNNmmmmNNNNNNNNNNNNNmmNNmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd
dmmmmmmmmmmmmNmmmmmmmmmmmNNNNNNNNNNmNNNmmNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNmNNmNNNNNmdo`` `  ``   `.s./hNNNNNNNNmNmmdsooshmNNN+``````````:mNNNNNNmNmNmNNNNNNNNNNmNmmmmNNNNmmNNmmNmmNmmmNmNNNNNmmmmNNNNNNNNNNmmNmmmmmNmmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmdm
dmmmmmmmmmmmmmmmmmmmmmmmNNNNNNmNNmmmmmmmmNmNNNNNNmNNNNNNNNNNNNNNNNNNNNNmNNmmmNNNNNmmd+` ``` ` ` `:s/yNNNNNNmNNmhsooydNNNNNmNNNs````````+mmmNNNNNNNNNNmNNNNNNNNNNNmmNmmmmmmmmNNNmmmmmmmmmmmNNNmmmmmNmNNNmNmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmd
mmmmmmmmmmmmmmmmmmmdmmmmNNNNmNmNNmmmNmmNNmNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNmd/```````` `:oohNNNNNNNdsooymmNNNNNNNNNNNNNh.````.ymmmNNNNNNNNNNmmNNNNNNNNmNmmmmmmmNmmmmmmmmmmmNmmNmNNNNNNNNmNNNmNNmmNNNmNmmmmmNmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
```

Priority 0.
